### ISSUE TITLE
some erro

### ISSUE THREAD

**Issue by LELUSHU** [asoplata/propofol-coupling-2017-full#1]
Dear Austin E. Soplata:
 when we run the code which is p1d1w2f2s2to3r1_20170106_simple_propo in fig2 folder  in matlab, common window output "invalide field name : TC_\DynaSim-master\models\iKLeakChing2010TC.mech_gKleak".we have tried to change modles folder in different folders ,but we can't run this code correctly. matlab can't recognize code like "iKLeakChing2010TC " and so on .

**Comment by asoplata** [comment]
Thank you for your interest in my code! I will try to investigate this later today. In the meantime, here are some possible solutions:

- Make sure every mechanism file ends with the ".mech" filetype extension. For example, if your filename is "iKLeakChing2010TC.mech_gKleak", please change it to "iKLeakChing2010TC.mech", since DynaSim looks for files with that extension specifically.
- Make that all your mechanism files are either 1. in the "models" folder itself and not a subfolder, OR 2. in any subfolder inside the "models/personal" folder. I believe that DynaSim only looks in these locations for mechanism files.

I will try to test this code again today and see if I can reproduce the issue. Note that this code was run on a 2016 or 2015 version of MATLAB, and I have not tested it on newer versions.

**Comment by LELUSHU** [comment]
your answers are very important for us ! we have solved the issue mentioned in first conversation. And we met some new issue.
 first, we guess that your code was written by using a linux system conputer. And we just have windows system computer.so ,we met many bug It's that true? 
second ,when we run the modle which is p1d1w2f2s2to3r1_20170106_simple_propo in fig2 folder in matlab, fname in Line 600  in simulatemodle.m which is   [outputs{1:length(output_variables)}]=feval(fname) will creat a  variable with long name and @current in this variable can't be found.we tried many times ,but we can't solved this issue. 

We look forward to hearing from you!!!!!!!

**Comment by asoplata** [comment]
1. Yes, my code was written on Linux. However, there is only one change that should be required in the script `p1d1w2f2s2to3r1_20170106_simple_propo.m` to have it work on Windows: the variable for the output data, `data_dir` on [Line 99](https://github.com/asoplata/propofol-coupling-2017-full/blob/master/runscripts/Fig2/p1d1w2f2s2to3r1_20170106_simple_propo.m#L99 ) needs to be adapted for Windows (which uses "\") instead of Linux (which uses "/"). For example, if you want the output data to go to some place like `C:\Users\Lelushu\propofol_data` instead of the directory currently set, change the path to that from `/projectnb/crc-nak/asoplata/dynasim_data/`. Note that Windows uses backslash \ in its path names, while Linux uses forwardslash / , so you'll have to change that. If this does not solve the Windows issue, then I will need more information to solve any Windows/Linux issues.

2. Is there an actual error related to *@ current* that Matlab reports which prevents the simulation being run, or are you saying that you cannot find *@ current* in the output code? If it is the first case where there's an actual error preventing the simulation from running, please copy and paste the contents of your `simulatemodle.m` file either here in this issue thread, or email me personally with the file so I can investigate the bug. If the problem is that you cannot find the `current` variable, that is because `current` is a "dummy variable" that is not actually used, but instead tells DynaSim where to add the current or dV/dt portion of a channel into the neuron model itself. In other words, in the optimized code file that is generated to run the actual simulation, I believe there is no "current" variable, because those parts of the equations are used in the ODE equations for the V voltage variables.

* edited to not mention the GitHub @ current user

**Comment by asoplata** [comment]
Was this issue resolved @LELUSHU  ?
